apiVersion: v1
kind: Secret
metadata:
  name: shieldnet-secrets
  namespace: shieldnet
type: Opaque
stringData:
  INFLUXDB_PASSWORD: changeme
  JWT_SECRET: changeme
  KAFKA_SASL_PASSWORD: changeme
  DATABASE_PASSWORD: changeme
