apiVersion: v1
kind: Service
metadata:
  name: sn-fl-client
  namespace: shieldnet
spec:
  selector:
    app: sn-fl-client
  ports:
  - port: 8004
    targetPort: 8004
    name: grpc
  type: ClusterIP
