apiVersion: v1
kind: Service
metadata:
  name: sn-fl-server
  namespace: shieldnet
spec:
  selector:
    app: sn-fl-server
  ports:
  - port: 9080
    targetPort: 9080
    name: grpc
  type: ClusterIP
