import json
import time
import logging

logger = logging.getLogger("shieldnet.airo.reporter")


class IncidentReporter:
    def __init__(self, influx_url: str = ""):
        self.influx_url = influx_url
        self._incidents = []

    def record_incident(self, incident: dict):
        self._incidents.append(incident)
        logger.info(f"Incident recorded: {incident.get('incident_id')} - "
                     f"{incident.get('threat_class')} - "
                     f"containment: {incident.get('containment_time_ms')}ms")

    def get_incident(self, incident_id: str) -> dict:
        for inc in self._incidents:
            if inc.get("incident_id") == incident_id:
                return inc
        return {}

    def get_all_incidents(self, limit: int = 50, offset: int = 0,
                          zone_id: str = "", status: str = "",
                          threat_class: str = "") -> list:
        results = self._incidents[::-1]
        if zone_id:
            results = [i for i in results if i.get("zone_id") == zone_id]
        if status:
            results = [i for i in results if i.get("status") == status]
        if threat_class:
            results = [i for i in results if i.get("threat_class") == threat_class]
        return results[offset:offset + limit]

    def total_count(self, zone_id: str = "", status: str = "",
                    threat_class: str = "") -> int:
        return len(self.get_all_incidents(limit=999999, zone_id=zone_id,
                                          status=status, threat_class=threat_class))

    def mark_false_positive(self, incident_id: str, operator_id: str = "",
                            notes: str = ""):
        inc = self.get_incident(incident_id)
        if inc:
            inc["false_positive_confirmed"] = True
            inc["status"] = "FALSE_POSITIVE"
            inc["operator_id"] = operator_id
            inc["operator_notes"] = notes
            logger.info(f"Incident {incident_id} marked as false positive")

    def update_status(self, incident_id: str, status: str):
        inc = self.get_incident(incident_id)
        if inc:
            inc["status"] = status

    def generate_report_summary(self, incident_id: str) -> str:
        inc = self.get_incident(incident_id)
        if not inc:
            return "Incident not found"
        lines = [
            "ShieldNet Incident Report",
            "=" * 60,
            f"Incident ID    : {inc.get('incident_id')}",
            f"Classification : CONFIDENTIAL - OPERATIONAL SECURITY",
            f"Generated By   : ShieldNet SOC v1.0",
            f"Generated At   : {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}",
            "",
            "1. EXECUTIVE SUMMARY",
            f"  A {inc.get('threat_class')} attack was detected and automatically",
            f"  contained by ShieldNet AIRO at {inc.get('zone_id')}.",
            f"  Containment time: {inc.get('containment_time_ms')}ms from detection.",
            "",
            "2. DETECTION DETAILS",
            f"  Detection Time   : {inc.get('timestamp_detected')}",
            f"  Containment Time : {inc.get('timestamp_contained')}",
            f"  Total Time       : {inc.get('containment_time_ms')} ms",
            f"  Zone             : {inc.get('zone_id')}",
            f"  Device Category  : {inc.get('device_category')}",
            f"  Threat Class     : {inc.get('threat_class')}",
            "",
            "3. MODEL SCORES",
            f"  LSTM Score       : {inc.get('individual_scores', {}).get('lstm', 'N/A')}",
            f"  Isolation Forest : {inc.get('individual_scores', {}).get('isolation_forest', 'N/A')}",
            f"  Autoencoder      : {inc.get('individual_scores', {}).get('autoencoder', 'N/A')}",
            f"  Ensemble Score   : {inc.get('confidence_score')}",
            f"  Decision         : {inc.get('status')}",
            "",
            "4. AIRO ACTIONS TAKEN",
        ]
        for action in inc.get("actions_taken", []):
            lines.append(f"  - {action}")
        lines.extend([
            "",
            "5. POST-INCIDENT STATUS",
            f"  Device status   : CONTAINED",
            f"  Auto-restore    : Scheduled",
            "",
            "SIGNATURE",
            "  Generated by ShieldNet v1.0 | INTELLIFY 2025 | ALPHA401",
        ])
        return "\n".join(lines)
